{
 "title": "OpenTelemetry Collector",
 "description": "Provides information about the status of the OpenTelemetry Collector",
 "tags": [
  "opentelemetry",
  "opentelemetry-collector"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(otelcol_process_uptime_seconds_total, job)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "description": "OTel Collectors. Derived from the `otelcol.process.uptime` metric.",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "otelcol_process_uptime_seconds_total{job=~\"$job\"}",
     "legendFormat": "{{service_name}} {{service_instance_id}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 6, "x": 17, "y": 1 } },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 }, "options": { "content": "Receivers" } },
  {
   "title": "Spans",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans_total{job=~\"$job\"}[$__rate_interval]))\n+\nsum(rate(otelcol_receiver_refused_spans_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Span Rate"
    }
   ]
  },
  {
   "title": "Span Errors",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1\n- \nsum(\n  rate(\n    otelcol_receiver_accepted_spans_total{\n      deployment_environment_name=~\"$deployment_environment_name\",\n      k8s_cluster_name=~\"$k8s_cluster_name\",\n      k8s_node_name=~\"$k8s_node_name\",\n      host_name=~\"$host_name\",\n      service_instance_id=~\"$service_instance_id\",\n      service_name=~\"$service_name\"\n    }[$__rate_interval]\n  )\n)\n/\n(\n  sum(\n    rate(\n      otelcol_receiver_accepted_spans_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_receiver_refused_spans_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_receiver_failed_spans_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "Span Errors"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "stat",
   "description": "Aggregate ingestion rate across all receivers by telemetry type",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_log_records_total{job=~\"$job\"}[$__rate_interval]))\n+\nsum(rate(otelcol_receiver_refused_log_records_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Log Errors",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1\n-\nsum(\n  rate(\n    otelcol_receiver_accepted_log_records_total{\n      deployment_environment_name=~\"$deployment_environment_name\",\n      k8s_cluster_name=~\"$k8s_cluster_name\",\n      k8s_node_name=~\"$k8s_node_name\",\n      host_name=~\"$host_name\",\n      service_instance_id=~\"$service_instance_id\",\n      service_name=~\"$service_name\"\n    }[$__rate_interval]\n  )\n)\n/\n(\n  sum(\n    rate(\n      otelcol_receiver_accepted_log_records_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_receiver_refused_log_records_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_receiver_failed_log_records_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Aggregate ingestion rate across all receivers by telemetry type",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points_total{job=~\"$job\"}[$__rate_interval]))\n+\nsum(rate(otelcol_receiver_refused_metric_points_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Metrics"
    }
   ]
  },
  {
   "title": "Metric Errors",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1\n-\nsum(\n  rate(\n    otelcol_receiver_accepted_metric_points_total{\n      deployment_environment_name=~\"$deployment_environment_name\",\n      k8s_cluster_name=~\"$k8s_cluster_name\",\n      k8s_node_name=~\"$k8s_node_name\",\n      host_name=~\"$host_name\",\n      service_instance_id=~\"$service_instance_id\",\n      service_name=~\"$service_name\"\n    }[$__rate_interval]\n  )\n)\n/\n(\n  sum(\n    rate(\n      otelcol_receiver_accepted_metric_points_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_receiver_refused_metric_points_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_receiver_failed_metric_points_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "Metrics"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 }, "options": { "content": "Processors" } },
  {
   "title": "Spans",
   "type": "stat",
   "description": "Span processors inbound rate, aggregated across all processors",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (otel_signal) (\n  rate(\n    otelcol_processor_incoming_items_total{\n      deployment_environment_name =~ \"$deployment_environment_name\",\n      k8s_cluster_name           =~ \"$k8s_cluster_name\",\n      k8s_node_name              =~ \"$k8s_node_name\",\n      host_name                  =~ \"$host_name\",\n      service_instance_id        =~ \"$service_instance_id\",\n      service_name               =~ \"$service_name\",\n      otel_signal                =  \"traces\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drop Rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (otel_signal) (\n    rate(\n      otelcol_processor_incoming_items_total{\n        deployment_environment_name =~ \"$deployment_environment_name\",\n        k8s_cluster_name           =~ \"$k8s_cluster_name\",\n        k8s_node_name              =~ \"$k8s_node_name\",\n        host_name                  =~ \"$host_name\",\n        service_instance_id        =~ \"$service_instance_id\",\n        service_name               =~ \"$service_name\",\n        otel_signal                =  \"traces\"\n      }[$__rate_interval]\n    )\n  )\n-\n  sum by (otel_signal) (\n    rate(\n      otelcol_processor_outgoing_items_total{\n        deployment_environment_name =~ \"$deployment_environment_name\",\n        k8s_cluster_name           =~ \"$k8s_cluster_name\",\n        k8s_node_name              =~ \"$k8s_node_name\",\n        host_name                  =~ \"$host_name\",\n        service_instance_id        =~ \"$service_instance_id\",\n        service_name               =~ \"$service_name\",\n        otel_signal                =  \"traces\"\n      }[$__rate_interval]\n    )\n  )\n)\n/\nsum by (otel_signal) (\n  rate(\n    otelcol_processor_incoming_items_total{\n      deployment_environment_name =~ \"$deployment_environment_name\",\n      k8s_cluster_name           =~ \"$k8s_cluster_name\",\n      k8s_node_name              =~ \"$k8s_node_name\",\n      host_name                  =~ \"$host_name\",\n      service_instance_id        =~ \"$service_instance_id\",\n      service_name               =~ \"$service_name\",\n      otel_signal                =  \"traces\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Drop Rate"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "stat",
   "description": "Logs processors inbound rate, aggregated across all processors",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (otel_signal) (\n  rate(\n    otelcol_processor_incoming_items_total{\n      deployment_environment_name =~ \"$deployment_environment_name\",\n      k8s_cluster_name           =~ \"$k8s_cluster_name\",\n      k8s_node_name              =~ \"$k8s_node_name\",\n      host_name                  =~ \"$host_name\",\n      service_instance_id        =~ \"$service_instance_id\",\n      service_name               =~ \"$service_name\",\n      otel_signal                =  \"logs\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drop Rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (otel_signal) (\n    rate(\n      otelcol_processor_incoming_items_total{\n        deployment_environment_name =~ \"$deployment_environment_name\",\n        k8s_cluster_name           =~ \"$k8s_cluster_name\",\n        k8s_node_name              =~ \"$k8s_node_name\",\n        host_name                  =~ \"$host_name\",\n        service_instance_id        =~ \"$service_instance_id\",\n        service_name               =~ \"$service_name\",\n        otel_signal                =  \"logs\"\n      }[$__rate_interval]\n    )\n  )\n-\n  sum by (otel_signal) (\n    rate(\n      otelcol_processor_outgoing_items_total{\n        deployment_environment_name =~ \"$deployment_environment_name\",\n        k8s_cluster_name           =~ \"$k8s_cluster_name\",\n        k8s_node_name              =~ \"$k8s_node_name\",\n        host_name                  =~ \"$host_name\",\n        service_instance_id        =~ \"$service_instance_id\",\n        service_name               =~ \"$service_name\",\n        otel_signal                =  \"logs\"\n      }[$__rate_interval]\n    )\n  )\n)\n/\nsum by (otel_signal) (\n  rate(\n    otelcol_processor_incoming_items_total{\n      deployment_environment_name =~ \"$deployment_environment_name\",\n      k8s_cluster_name           =~ \"$k8s_cluster_name\",\n      k8s_node_name              =~ \"$k8s_node_name\",\n      host_name                  =~ \"$host_name\",\n      service_instance_id        =~ \"$service_instance_id\",\n      service_name               =~ \"$service_name\",\n      otel_signal                =  \"logs\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Drop Rate"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Metrics processors inbound rate, aggregated across all processors",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (otel_signal) (\n  rate(\n    otelcol_processor_incoming_items_total{\n      deployment_environment_name =~ \"$deployment_environment_name\",\n      k8s_cluster_name           =~ \"$k8s_cluster_name\",\n      k8s_node_name              =~ \"$k8s_node_name\",\n      host_name                  =~ \"$host_name\",\n      service_instance_id        =~ \"$service_instance_id\",\n      service_name               =~ \"$service_name\",\n      otel_signal                =  \"metrics\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drop Rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (otel_signal) (\n    rate(\n      otelcol_processor_incoming_items_total{\n        deployment_environment_name =~ \"$deployment_environment_name\",\n        k8s_cluster_name           =~ \"$k8s_cluster_name\",\n        k8s_node_name              =~ \"$k8s_node_name\",\n        host_name                  =~ \"$host_name\",\n        service_instance_id        =~ \"$service_instance_id\",\n        service_name               =~ \"$service_name\",\n        otel_signal                =  \"metrics\"\n      }[$__rate_interval]\n    )\n  )\n-\n  sum by (otel_signal) (\n    rate(\n      otelcol_processor_outgoing_items_total{\n        deployment_environment_name =~ \"$deployment_environment_name\",\n        k8s_cluster_name           =~ \"$k8s_cluster_name\",\n        k8s_node_name              =~ \"$k8s_node_name\",\n        host_name                  =~ \"$host_name\",\n        service_instance_id        =~ \"$service_instance_id\",\n        service_name               =~ \"$service_name\",\n        otel_signal                =  \"metrics\"\n      }[$__rate_interval]\n    )\n  )\n)\n/\nsum by (otel_signal) (\n  rate(\n    otelcol_processor_incoming_items_total{\n      deployment_environment_name =~ \"$deployment_environment_name\",\n      k8s_cluster_name           =~ \"$k8s_cluster_name\",\n      k8s_node_name              =~ \"$k8s_node_name\",\n      host_name                  =~ \"$host_name\",\n      service_instance_id        =~ \"$service_instance_id\",\n      service_name               =~ \"$service_name\",\n      otel_signal                =  \"metrics\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Drop Rate"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 }, "options": { "content": "Exporters" } },
  {
   "title": "Spans",
   "type": "stat",
   "description": "Aggregated spans export rate across all exporters",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Spans"
    }
   ]
  },
  {
   "title": "Span Errors",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1\n- \nsum(\n  rate(\n    otelcol_receiver_accepted_spans_total{\n      deployment_environment_name=~\"$deployment_environment_name\",\n      k8s_cluster_name=~\"$k8s_cluster_name\",\n      k8s_node_name=~\"$k8s_node_name\",\n      host_name=~\"$host_name\",\n      service_instance_id=~\"$service_instance_id\",\n      service_name=~\"$service_name\"\n    }[$__rate_interval]\n  )\n)\n/\n(\n  sum(\n    rate(\n      otelcol_receiver_accepted_spans_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_receiver_refused_spans_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_receiver_failed_spans_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "Span Errors"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "stat",
   "description": "Aggregated logs export rate across all exporters",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_log_records_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Logs Errors",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1\n-\nsum(\n  rate(\n    otelcol_exporter_sent_log_records_total{\n      deployment_environment_name=~\"$deployment_environment_name\",\n      k8s_cluster_name=~\"$k8s_cluster_name\",\n      k8s_node_name=~\"$k8s_node_name\",\n      host_name=~\"$host_name\",\n      service_instance_id=~\"$service_instance_id\",\n      service_name=~\"$service_name\"\n    }[$__rate_interval]\n  )\n)\n/\n(\n  sum(\n    rate(\n      otelcol_exporter_sent_log_records_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_exporter_send_failed_log_records_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Aggregate metrics export rate across all exporters",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Metrics"
    }
   ]
  },
  {
   "title": "Metrics Errors",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1\n-\nsum(\n  rate(\n    otelcol_exporter_sent_metric_points_total{\n      deployment_environment_name=~\"$deployment_environment_name\",\n      k8s_cluster_name=~\"$k8s_cluster_name\",\n      k8s_node_name=~\"$k8s_node_name\",\n      host_name=~\"$host_name\",\n      service_instance_id=~\"$service_instance_id\",\n      service_name=~\"$service_name\"\n    }[$__rate_interval]\n  )\n)\n/\n(\n  sum(\n    rate(\n      otelcol_exporter_sent_metric_points_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_exporter_send_failed_metric_points_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "Metrics"
    }
   ]
  },
  {
   "title": "Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "OTel Collectors. Derived from the `otelcol.process.uptime` metric.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "otelcol_process_uptime_seconds_total{job=~\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "stat",
     "description": "CPU consumption rate of the OpenTelemetry collector process",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(otelcol_process_cpu_seconds_total{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{service_name}} {{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Memory Usage (RSS)",
     "type": "stat",
     "description": "Resident memory consumed by the OpenTelemetry collector process",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "otelcol_process_memory_rss_bytes{job=~\"$job\"}",
       "legendFormat": "{{service_name}} {{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "Total uptime of the OpenTelemetry collector process",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "otelcol_process_uptime_seconds_total{job=~\"$job\"}",
       "legendFormat": "{{service_name}} {{service_instance_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Receivers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Span Rate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_receiver_accepted_spans_total{job=~\"$job\"}[$__rate_interval]))\n+\nsum(rate(otelcol_receiver_refused_spans_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "Span Rate"
      }
     ]
    },
    {
     "title": "Span Errors",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 2, "x": 3, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1\n- \nsum(\n  rate(\n    otelcol_receiver_accepted_spans_total{\n      deployment_environment_name=~\"$deployment_environment_name\",\n      k8s_cluster_name=~\"$k8s_cluster_name\",\n      k8s_node_name=~\"$k8s_node_name\",\n      host_name=~\"$host_name\",\n      service_instance_id=~\"$service_instance_id\",\n      service_name=~\"$service_name\"\n    }[$__rate_interval]\n  )\n)\n/\n(\n  sum(\n    rate(\n      otelcol_receiver_accepted_spans_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_receiver_refused_spans_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_receiver_failed_spans_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n)",
       "legendFormat": "Span Errors"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "stat",
     "description": "Aggregate ingestion rate across all receivers by telemetry type",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_receiver_accepted_log_records_total{job=~\"$job\"}[$__rate_interval]))\n+\nsum(rate(otelcol_receiver_refused_log_records_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "Logs"
      }
     ]
    },
    {
     "title": "Log Errors",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1\n-\nsum(\n  rate(\n    otelcol_receiver_accepted_log_records_total{\n      deployment_environment_name=~\"$deployment_environment_name\",\n      k8s_cluster_name=~\"$k8s_cluster_name\",\n      k8s_node_name=~\"$k8s_node_name\",\n      host_name=~\"$host_name\",\n      service_instance_id=~\"$service_instance_id\",\n      service_name=~\"$service_name\"\n    }[$__rate_interval]\n  )\n)\n/\n(\n  sum(\n    rate(\n      otelcol_receiver_accepted_log_records_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_receiver_refused_log_records_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_receiver_failed_log_records_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n)",
       "legendFormat": "Logs"
      }
     ]
    },
    {
     "title": "Metrics",
     "type": "stat",
     "description": "Aggregate ingestion rate across all receivers by telemetry type",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_receiver_accepted_metric_points_total{job=~\"$job\"}[$__rate_interval]))\n+\nsum(rate(otelcol_receiver_refused_metric_points_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "Metrics"
      }
     ]
    },
    {
     "title": "Metric Errors",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 2, "x": 13, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1\n-\nsum(\n  rate(\n    otelcol_receiver_accepted_metric_points_total{\n      deployment_environment_name=~\"$deployment_environment_name\",\n      k8s_cluster_name=~\"$k8s_cluster_name\",\n      k8s_node_name=~\"$k8s_node_name\",\n      host_name=~\"$host_name\",\n      service_instance_id=~\"$service_instance_id\",\n      service_name=~\"$service_name\"\n    }[$__rate_interval]\n  )\n)\n/\n(\n  sum(\n    rate(\n      otelcol_receiver_accepted_metric_points_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_receiver_refused_metric_points_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_receiver_failed_metric_points_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n)",
       "legendFormat": "Metrics"
      }
     ]
    },
    {
     "title": "Receivers",
     "type": "table",
     "description": "Detailed breakdown by receiver and telemetry type",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (signal_type_receiver) (\n  label_join(\n    label_replace(\n      sum by (receiver) (\n        rate(\n          otelcol_receiver_accepted_spans_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n        +\n        rate(\n          otelcol_receiver_refused_spans_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      ),\n      \"signal_type\",\n      \"traces\",\n      \"\",\n      \"\"\n    )\n    or\n    label_replace(\n      sum by (receiver) (\n        rate(\n          otelcol_receiver_accepted_log_records_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n        +\n        rate(\n          otelcol_receiver_refused_log_records_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      ),\n      \"signal_type\",\n      \"logs\",\n      \"\",\n      \"\"\n    )\n    or\n    label_replace(\n      sum by (receiver) (\n        rate(\n          otelcol_receiver_accepted_metric_points_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n        +\n        rate(\n          otelcol_receiver_refused_metric_points_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      ),\n      \"signal_type\",\n      \"metrics\",\n      \"\",\n      \"\"\n    )\n    ,\n    \"signal_type_receiver\",\n    \"-\",\n    \"signal_type\",\n    \"receiver\"\n  )\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (signal_type_receiver) (\n  label_join(\n    label_replace(\n      sum by (receiver) (\n        rate(\n          otelcol_receiver_refused_spans_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      ),\n      \"signal_type\",\n      \"traces\",\n      \"\",\n      \"\"\n    )\n    or\n    label_replace(\n      sum by (receiver) (\n        rate(\n          otelcol_receiver_refused_log_records_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      ),\n      \"signal_type\",\n      \"logs\",\n      \"\",\n      \"\"\n    )\n    or\n    label_replace(\n      sum by (receiver) (\n        rate(\n          otelcol_receiver_refused_metric_points_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      ),\n      \"signal_type\",\n      \"metrics\",\n      \"\",\n      \"\"\n    )\n    ,\n    \"signal_type_receiver\",\n    \"-\",\n    \"signal_type\",\n    \"receiver\"\n  )\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (signal_type_receiver) (\n  label_join(\n    label_replace(\n      sum by (receiver) (\n        rate(\n          otelcol_receiver_failed_spans_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      ),\n      \"signal_type\",\n      \"traces\",\n      \"\",\n      \"\"\n    )\n    or\n    label_replace(\n      sum by (receiver) (\n        rate(\n          otelcol_receiver_failed_log_records_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      ),\n      \"signal_type\",\n      \"logs\",\n      \"\",\n      \"\"\n    )\n    or\n    label_replace(\n      sum by (receiver) (\n        rate(\n          otelcol_receiver_failed_metric_points_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      ),\n      \"signal_type\",\n      \"metrics\",\n      \"\",\n      \"\"\n    )\n    ,\n    \"signal_type_receiver\",\n    \"-\",\n    \"signal_type\",\n    \"receiver\"\n  )\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (signal_type_receiver) (\n  label_join(\n    label_replace(\n      (\n        sum by (receiver) (\n          rate(\n            otelcol_receiver_refused_spans_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n          +\n          rate(\n            otelcol_receiver_failed_spans_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n        )\n        /\n        sum by (receiver) (\n          rate(\n            otelcol_receiver_accepted_spans_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n          +\n          rate(\n            otelcol_receiver_refused_spans_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n          +\n          rate(\n            otelcol_receiver_failed_spans_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n        )\n      ) * 100,\n      \"signal_type\",\n      \"traces\",\n      \"\",\n      \"\"\n    )\n    or\n    label_replace(\n      (\n        sum by (receiver) (\n          rate(\n            otelcol_receiver_refused_log_records_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n          +\n          rate(\n            otelcol_receiver_failed_log_records_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n        )\n        /\n        sum by (receiver) (\n          rate(\n            otelcol_receiver_accepted_log_records_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n          +\n          rate(\n            otelcol_receiver_refused_log_records_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n          +\n          rate(\n            otelcol_receiver_failed_log_records_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n        )\n      ) * 100,\n      \"signal_type\",\n      \"logs\",\n      \"\",\n      \"\"\n    )\n    or\n    label_replace(\n      (\n        sum by (receiver) (\n          rate(\n            otelcol_receiver_refused_metric_points_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n          +\n          rate(\n            otelcol_receiver_failed_metric_points_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n        )\n        /\n        sum by (receiver) (\n          rate(\n            otelcol_receiver_accepted_metric_points_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n          +\n          rate(\n            otelcol_receiver_refused_metric_points_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n          +\n          rate(\n            otelcol_receiver_failed_metric_points_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n        )\n      ) * 100,\n      \"signal_type\",\n      \"metrics\",\n      \"\",\n      \"\"\n    )\n    ,\n    \"signal_type_receiver\",\n    \"-\",\n    \"signal_type\",\n    \"receiver\"\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spans",
     "type": "stat",
     "description": "Span processors inbound rate, aggregated across all processors",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (otel_signal) (\n  rate(\n    otelcol_processor_incoming_items_total{\n      deployment_environment_name =~ \"$deployment_environment_name\",\n      k8s_cluster_name           =~ \"$k8s_cluster_name\",\n      k8s_node_name              =~ \"$k8s_node_name\",\n      host_name                  =~ \"$host_name\",\n      service_instance_id        =~ \"$service_instance_id\",\n      service_name               =~ \"$service_name\",\n      otel_signal                =  \"traces\"\n    }[$__rate_interval]\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Drop Rate",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 2, "x": 3, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by (otel_signal) (\n    rate(\n      otelcol_processor_incoming_items_total{\n        deployment_environment_name =~ \"$deployment_environment_name\",\n        k8s_cluster_name           =~ \"$k8s_cluster_name\",\n        k8s_node_name              =~ \"$k8s_node_name\",\n        host_name                  =~ \"$host_name\",\n        service_instance_id        =~ \"$service_instance_id\",\n        service_name               =~ \"$service_name\",\n        otel_signal                =  \"traces\"\n      }[$__rate_interval]\n    )\n  )\n-\n  sum by (otel_signal) (\n    rate(\n      otelcol_processor_outgoing_items_total{\n        deployment_environment_name =~ \"$deployment_environment_name\",\n        k8s_cluster_name           =~ \"$k8s_cluster_name\",\n        k8s_node_name              =~ \"$k8s_node_name\",\n        host_name                  =~ \"$host_name\",\n        service_instance_id        =~ \"$service_instance_id\",\n        service_name               =~ \"$service_name\",\n        otel_signal                =  \"traces\"\n      }[$__rate_interval]\n    )\n  )\n)\n/\nsum by (otel_signal) (\n  rate(\n    otelcol_processor_incoming_items_total{\n      deployment_environment_name =~ \"$deployment_environment_name\",\n      k8s_cluster_name           =~ \"$k8s_cluster_name\",\n      k8s_node_name              =~ \"$k8s_node_name\",\n      host_name                  =~ \"$host_name\",\n      service_instance_id        =~ \"$service_instance_id\",\n      service_name               =~ \"$service_name\",\n      otel_signal                =  \"traces\"\n    }[$__rate_interval]\n  )\n)",
       "legendFormat": "Drop Rate"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "stat",
     "description": "Logs processors inbound rate, aggregated across all processors",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (otel_signal) (\n  rate(\n    otelcol_processor_incoming_items_total{\n      deployment_environment_name =~ \"$deployment_environment_name\",\n      k8s_cluster_name           =~ \"$k8s_cluster_name\",\n      k8s_node_name              =~ \"$k8s_node_name\",\n      host_name                  =~ \"$host_name\",\n      service_instance_id        =~ \"$service_instance_id\",\n      service_name               =~ \"$service_name\",\n      otel_signal                =  \"logs\"\n    }[$__rate_interval]\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Drop Rate",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by (otel_signal) (\n    rate(\n      otelcol_processor_incoming_items_total{\n        deployment_environment_name =~ \"$deployment_environment_name\",\n        k8s_cluster_name           =~ \"$k8s_cluster_name\",\n        k8s_node_name              =~ \"$k8s_node_name\",\n        host_name                  =~ \"$host_name\",\n        service_instance_id        =~ \"$service_instance_id\",\n        service_name               =~ \"$service_name\",\n        otel_signal                =  \"logs\"\n      }[$__rate_interval]\n    )\n  )\n-\n  sum by (otel_signal) (\n    rate(\n      otelcol_processor_outgoing_items_total{\n        deployment_environment_name =~ \"$deployment_environment_name\",\n        k8s_cluster_name           =~ \"$k8s_cluster_name\",\n        k8s_node_name              =~ \"$k8s_node_name\",\n        host_name                  =~ \"$host_name\",\n        service_instance_id        =~ \"$service_instance_id\",\n        service_name               =~ \"$service_name\",\n        otel_signal                =  \"logs\"\n      }[$__rate_interval]\n    )\n  )\n)\n/\nsum by (otel_signal) (\n  rate(\n    otelcol_processor_incoming_items_total{\n      deployment_environment_name =~ \"$deployment_environment_name\",\n      k8s_cluster_name           =~ \"$k8s_cluster_name\",\n      k8s_node_name              =~ \"$k8s_node_name\",\n      host_name                  =~ \"$host_name\",\n      service_instance_id        =~ \"$service_instance_id\",\n      service_name               =~ \"$service_name\",\n      otel_signal                =  \"logs\"\n    }[$__rate_interval]\n  )\n)",
       "legendFormat": "Drop Rate"
      }
     ]
    },
    {
     "title": "Metrics",
     "type": "stat",
     "description": "Metrics processors inbound rate, aggregated across all processors",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (otel_signal) (\n  rate(\n    otelcol_processor_incoming_items_total{\n      deployment_environment_name =~ \"$deployment_environment_name\",\n      k8s_cluster_name           =~ \"$k8s_cluster_name\",\n      k8s_node_name              =~ \"$k8s_node_name\",\n      host_name                  =~ \"$host_name\",\n      service_instance_id        =~ \"$service_instance_id\",\n      service_name               =~ \"$service_name\",\n      otel_signal                =  \"metrics\"\n    }[$__rate_interval]\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Drop Rate",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 2, "x": 13, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by (otel_signal) (\n    rate(\n      otelcol_processor_incoming_items_total{\n        deployment_environment_name =~ \"$deployment_environment_name\",\n        k8s_cluster_name           =~ \"$k8s_cluster_name\",\n        k8s_node_name              =~ \"$k8s_node_name\",\n        host_name                  =~ \"$host_name\",\n        service_instance_id        =~ \"$service_instance_id\",\n        service_name               =~ \"$service_name\",\n        otel_signal                =  \"metrics\"\n      }[$__rate_interval]\n    )\n  )\n-\n  sum by (otel_signal) (\n    rate(\n      otelcol_processor_outgoing_items_total{\n        deployment_environment_name =~ \"$deployment_environment_name\",\n        k8s_cluster_name           =~ \"$k8s_cluster_name\",\n        k8s_node_name              =~ \"$k8s_node_name\",\n        host_name                  =~ \"$host_name\",\n        service_instance_id        =~ \"$service_instance_id\",\n        service_name               =~ \"$service_name\",\n        otel_signal                =  \"metrics\"\n      }[$__rate_interval]\n    )\n  )\n)\n/\nsum by (otel_signal) (\n  rate(\n    otelcol_processor_incoming_items_total{\n      deployment_environment_name =~ \"$deployment_environment_name\",\n      k8s_cluster_name           =~ \"$k8s_cluster_name\",\n      k8s_node_name              =~ \"$k8s_node_name\",\n      host_name                  =~ \"$host_name\",\n      service_instance_id        =~ \"$service_instance_id\",\n      service_name               =~ \"$service_name\",\n      otel_signal                =  \"metrics\"\n    }[$__rate_interval]\n  )\n)",
       "legendFormat": "Drop Rate"
      }
     ]
    },
    {
     "title": "Processors",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "sum by (otel_signal_processor)(\n  label_join(\n    (\n      sum by(processor, otel_signal) (\n        rate(otelcol_processor_outgoing_items_total{\n          deployment_environment_name=~\"$deployment_environment_name\",\n          k8s_cluster_name=~\"$k8s_cluster_name\",\n          k8s_node_name=~\"$k8s_node_name\",\n          host_name=~\"$host_name\",\n          service_instance_id=~\"$service_instance_id\",\n          service_name=~\"$service_name\"\n        }[$__rate_interval])\n      )\n      -\n      sum by(processor, otel_signal) (\n        rate(otelcol_processor_incoming_items_total{\n          deployment_environment_name=~\"$deployment_environment_name\",\n          k8s_cluster_name=~\"$k8s_cluster_name\",\n          k8s_node_name=~\"$k8s_node_name\",\n          host_name=~\"$host_name\",\n          service_instance_id=~\"$service_instance_id\",\n          service_name=~\"$service_name\"\n        }[$__rate_interval])\n      )\n    )\n    /\n    sum by(processor, otel_signal) (\n      rate(otelcol_processor_incoming_items_total{\n          deployment_environment_name=~\"$deployment_environment_name\",\n          k8s_cluster_name=~\"$k8s_cluster_name\",\n          k8s_node_name=~\"$k8s_node_name\",\n          host_name=~\"$host_name\",\n          service_instance_id=~\"$service_instance_id\",\n          service_name=~\"$service_name\"\n      }[$__rate_interval])\n    ),\n    \"otel_signal_processor\",\n    \"-\",\n    \"otel_signal\",\n    \"processor\"\n  )\n)"
      },
      {
       "expr": "sum by (otel_signal_processor)(\n  label_join(\n    sum by(processor, otel_signal) (\n      rate(otelcol_processor_incoming_items_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval])\n    ),\n    \"otel_signal_processor\",\n    \"-\",\n    \"otel_signal\",\n    \"processor\"\n  )\n)"
      },
      {
       "expr": "sum by (otel_signal_processor)(\n  label_join(\n    sum by(processor, otel_signal) (\n      rate(otelcol_processor_outgoing_items_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval])\n    ),\n    \"otel_signal_processor\",\n    \"-\",\n    \"otel_signal\",\n    \"processor\"\n  )\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spans",
     "type": "stat",
     "description": "Aggregated spans export rate across all exporters",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_exporter_sent_spans_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "Spans"
      }
     ]
    },
    {
     "title": "Span Errors",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 2, "x": 3, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1\n-\nsum(\n  rate(\n    otelcol_exporter_sent_spans_total{\n      deployment_environment_name=~\"$deployment_environment_name\",\n      k8s_cluster_name=~\"$k8s_cluster_name\",\n      k8s_node_name=~\"$k8s_node_name\",\n      host_name=~\"$host_name\",\n      service_instance_id=~\"$service_instance_id\",\n      service_name=~\"$service_name\"\n    }[$__rate_interval]\n  )\n)\n/\n(\n  sum(\n    rate(\n      otelcol_exporter_sent_spans_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_exporter_send_failed_spans_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n)",
       "legendFormat": "Spans"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "stat",
     "description": "Aggregated logs export rate across all exporters",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_exporter_sent_log_records_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "Logs"
      }
     ]
    },
    {
     "title": "Logs Errors",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1\n-\nsum(\n  rate(\n    otelcol_exporter_sent_log_records_total{\n      deployment_environment_name=~\"$deployment_environment_name\",\n      k8s_cluster_name=~\"$k8s_cluster_name\",\n      k8s_node_name=~\"$k8s_node_name\",\n      host_name=~\"$host_name\",\n      service_instance_id=~\"$service_instance_id\",\n      service_name=~\"$service_name\"\n    }[$__rate_interval]\n  )\n)\n/\n(\n  sum(\n    rate(\n      otelcol_exporter_sent_log_records_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_exporter_send_failed_log_records_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n)",
       "legendFormat": "Logs"
      }
     ]
    },
    {
     "title": "Metrics",
     "type": "stat",
     "description": "Aggregate metrics export rate across all exporters",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_exporter_sent_metric_points_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "Metrics"
      }
     ]
    },
    {
     "title": "Metrics Errors",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 2, "x": 13, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1\n-\nsum(\n  rate(\n    otelcol_exporter_sent_metric_points_total{\n      deployment_environment_name=~\"$deployment_environment_name\",\n      k8s_cluster_name=~\"$k8s_cluster_name\",\n      k8s_node_name=~\"$k8s_node_name\",\n      host_name=~\"$host_name\",\n      service_instance_id=~\"$service_instance_id\",\n      service_name=~\"$service_name\"\n    }[$__rate_interval]\n  )\n)\n/\n(\n  sum(\n    rate(\n      otelcol_exporter_sent_metric_points_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      otelcol_exporter_send_failed_metric_points_total{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n)",
       "legendFormat": "Metrics"
      }
     ]
    },
    {
     "title": "Exporters",
     "type": "table",
     "description": "Detailed breakdown by exporter and telemetry type",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 109 },
     "targets": [
      {
       "expr": "sum by (signal_type_exporter) (\n  label_join(\n    label_replace(\n      sum by (exporter) (\n        rate(\n          otelcol_exporter_sent_spans_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n        +\n        rate(\n          otelcol_exporter_send_failed_spans_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      ),\n      \"signal_type\",\n      \"traces\",\n      \"\",\n      \"\"\n    )\n    or\n    label_replace(\n      sum by (exporter) (\n        rate(\n          otelcol_exporter_sent_log_records_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n        +\n        rate(\n          otelcol_exporter_send_failed_log_records_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      ),\n      \"signal_type\",\n      \"logs\",\n      \"\",\n      \"\"\n    )\n    or\n    label_replace(\n      sum by (exporter) (\n        rate(\n          otelcol_exporter_sent_metric_points_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n        +\n        rate(\n          otelcol_exporter_send_failed_metric_points_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      ),\n      \"signal_type\",\n      \"metrics\",\n      \"\",\n      \"\"\n    )\n    ,\n    \"signal_type_exporter\",\n    \"-\",\n    \"signal_type\",\n    \"exporter\"\n  )\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (signal_type_exporter) (\n  label_join(\n    label_replace(\n      sum by (exporter) (\n        rate(\n          otelcol_exporter_send_failed_spans_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      )\n      /\n      (\n        sum by (exporter) (\n          rate(\n            otelcol_exporter_sent_spans_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n          +\n          rate(\n            otelcol_exporter_send_failed_spans_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n        )\n      )\n      * 100\n      ,\n      \"signal_type\",\n      \"traces\",\n      \"\",\n      \"\"\n    )\n    or\n    label_replace(\n      sum by (exporter) (\n        rate(\n          otelcol_exporter_send_failed_log_records_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      )\n      /\n      (\n        sum by (exporter) (\n          rate(\n            otelcol_exporter_sent_log_records_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n          +\n          rate(\n            otelcol_exporter_send_failed_log_records_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n        )\n      )\n      * 100\n      ,\n      \"signal_type\",\n      \"logs\",\n      \"\",\n      \"\"\n    )\n    or\n    label_replace(\n      sum by (exporter) (\n        rate(\n          otelcol_exporter_send_failed_metric_points_total{\n            deployment_environment_name=~\"$deployment_environment_name\",\n            k8s_cluster_name=~\"$k8s_cluster_name\",\n            k8s_node_name=~\"$k8s_node_name\",\n            host_name=~\"$host_name\",\n            service_instance_id=~\"$service_instance_id\",\n            service_name=~\"$service_name\"\n          }[$__rate_interval]\n        )\n      )\n      /\n      (\n        sum by (exporter) (\n          rate(\n            otelcol_exporter_sent_metric_points_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n          +\n          rate(\n            otelcol_exporter_send_failed_metric_points_total{\n              deployment_environment_name=~\"$deployment_environment_name\",\n              k8s_cluster_name=~\"$k8s_cluster_name\",\n              k8s_node_name=~\"$k8s_node_name\",\n              host_name=~\"$host_name\",\n              service_instance_id=~\"$service_instance_id\",\n              service_name=~\"$service_name\"\n            }[$__rate_interval]\n          )\n        )\n      )\n      * 100\n      ,\n      \"signal_type\",\n      \"metrics\",\n      \"\",\n      \"\"\n    )\n    ,\n    \"signal_type_exporter\",\n    \"-\",\n    \"signal_type\",\n    \"exporter\"\n  )\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (signal_type_exporter) (\n  label_join(\n    sum by (exporter, data_type) (\n      otelcol_exporter_queue_size{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }\n    )\n    ,\n    \"signal_type_exporter\",\n    \"-\",\n    \"data_type\",\n    \"exporter\"\n  )\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (signal_type_exporter) (\n  label_join(\n    sum by (exporter, data_type) (\n      otelcol_exporter_queue_size{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }\n      /\n      otelcol_exporter_queue_capacity{\n        deployment_environment_name=~\"$deployment_environment_name\",\n        k8s_cluster_name=~\"$k8s_cluster_name\",\n        k8s_node_name=~\"$k8s_node_name\",\n        host_name=~\"$host_name\",\n        service_instance_id=~\"$service_instance_id\",\n        service_name=~\"$service_name\"\n      }\n    )\n    ,\n    \"signal_type_exporter\",\n    \"-\",\n    \"data_type\",\n    \"exporter\"\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}