---
name: renovatebot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  renovate:
    uses: bendwyer/github-workflows/.github/workflows/renovatebot.yml@main
    with:
      gh_app_id: ${{ vars.GH_APP_ID }}
    secrets:
      gh_app_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
